# Generated by Django 5.2.1 on 2025-05-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassQatagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toliq_ism', models.CharField(max_length=150)),
                ('tavsif', models.TextField()),
                ('tugilgan_sana', models.DateField()),
                ('vafort_etgan_sana', models.DateField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': "Qatag'on",
                'verbose_name_plural': "Qatag'onlar",
                'db_table': 'qatagonlar',
                'ordering': ['toliq_ism'],
            },
        ),
    ]
