# Generated by Django 5.2.1 on 2025-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classqatagon',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='classqatagon',
            name='toliq_ism',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
