# Generated by Django 5.2.1 on 2025-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_classqatagon_slug_alter_classqatagon_toliq_ism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classqatagon',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
